### PR TITLE
Replaced Request with Axios

### PR DESCRIPTION
**Pull request by pratikpc**
As is well known, the [Request library has been deprecated](https://github.com/request/request/issues/3142).

As such, we need to replace Request with another.

A popular replacement is [Axios](https://github.com/axios/axios)

I have worked to ensure compatibility with Axios.
For example, while Axios uses `data` param, Request uses `json`
As such, I have retained both

One singular place this commit could be improved is in the portion dealing with Unit Tests

@kr1sp1n what's your view on this?

### CODE REVIEW

**Comment by Kamahl19** [comment]
@pratikpc I am not saying we shouldnt replace request, but Axios is not the best choice IMHO. It's not updated regularly, it introduces breaking changes in minor updates etc. I myself am migrating away from Axios. There are other options out there. 

Also request is a battle tested library. It does not need updates because it's just done. I agree with replacing deprecated software but not with worse software.

**Comment by pratikpc** [comment]
@Kamahl19 which library do you think can replace Request then if not Axios?

**Comment by fungiboletus** [comment]
What about [`got`](https://github.com/sindresorhus/got) ?

**Comment by ultimumdesign** [comment]
Any thoughts on this pull? I would love to utilize this package but dislike using a deprecated dependency for obvious reasons.

**Comment by tilgovi** [comment]
Maybe consider https://github.com/nodejs/undici

**Comment by irnnr** [comment]
Can we please get this moving, no matter what library? 
This issue in/with jest is caused by request https://github.com/request/request-promise/issues/247

**Comment by aphofstede** [comment]
Axios is as battle-tested as they come.
From their docs:
> Until axios reaches a 1.0 release, breaking changes will be released with a new minor version. For example 0.5.1, and 0.5.4 will have the same API, but 0.6.0 will have breaking changes.

That means, barring human error (which can always happen), you can still depend on their versioning and stick to patch releases if you want to be on the safe side.

Can we get a maintainer to comment on willingness-to-merge if conflicts get resolved?

**Comment by kr1sp1n** [comment]
@pratikpc Please resolve conflicts first. Thanks!

**Comment by aviadhahami** [comment]
this is conflicting and stale; Closing

[ nonetheless --> `requests` will be removed soon ]

**Comment by ChrisE217** [comment]
soon :) I'm happy to help out with the switch to axios/other alternatives

**Comment by aviadhahami** [comment]
I'm really trying, tho I can't push to npm 🤷‍♂️

**Comment by kr1sp1n** [comment]
@aviadhahami Hi, I created a npm org and will move the node-vault package to it so you can also manage the package. What is your npmjs handle?

**Comment by kr1sp1n** [comment]
Ah, found it: uiw4nk3r
Right?

**Comment by aviadhahami** [comment]
@kr1sp1n yes :) accepted it 👍
Note that I also require additional permissions to the repo in order to: create repository secrets (for deploy), remove stale CI/PR checks (travis #218), and probably future stuff 🙇‍♂️

**Comment by aviadhahami** [comment]
@kr1sp1n not sure how to view that; I did accept your invite this morgen tho.... any ideas?

**Comment by kr1sp1n** [comment]
@aviadhahami Did you activated 2FA on your npmjs account? I enforced 2FA on the org account. Maybe that's the problem?

**Comment by aviadhahami** [comment]
@kr1sp1n my 2FA is active 👍

**Pull request closed without merging**
