### PR TITLE
Change nodejs support

### PR DESCRIPTION
**Pull request by adam2k**
Add node support to travis and remove support for node 6 and 7.

### CODE REVIEW

**Comment by adam2k** [comment]
@kr1sp1n this is related to #189.  I'm attempting to remove `istanbul` and use `nyc` instead, but there isn't support for node versions older than 8 for `nyc` from what the tests are reporting in #189.

**Comment by adam2k** [comment]
@kr1sp1n anything we can help with to get some of these issues resolved?  Is it possible to add others to this repo as code reviewers?

**Comment by aviadhahami** [comment]
Trying to get this in asap :)

**Comment by aviadhahami** [comment]
@adam2k --> Travis was removed + Upgraded node; closing

**Pull request closed without merging**
