### PR TITLE
chore: add missing ldapLogin method in index.d.ts

### PR DESCRIPTION
**Pull request by fonimus**

### CODE REVIEW

**Comment by aviadhahami** [comment]
Lgtm 
I'm awaiting @kr1sp1n to grant me permissions to the CI so I can let them through

**Comment by kr1sp1n** [comment]
> Lgtm I'm awaiting @kr1sp1n to grant me permissions to the CI so I can let them through

It seems that travis-ci forces me to upgrade: 
"We are unable to start your build at this time. You exceeded the number of users allowed for your plan. Please review your plan details and follow the steps to resolution."
I am not willing to do that.
@aviadhahami Maybe you find a free solution to run the automated tests in a CI pipeline. You should have enough rights to change the CI/CD-Provider. If not then please reach out to me.

**Comment by aviadhahami** [comment]
@kr1sp1n I can use GH actions with no problem, no need for old Travis.

I am able to push new GH actions config but I can't (???) remove the current CI :/ and that's why I pinged 

Another part that's missing is how is the code being built and pushed the npm registry


I suggest we do a handover over zoom or equivalent and get it all sorted out and done with, wdyt?

**Comment by kr1sp1n** [comment]
@aviadhahami To remove the current CI we need to move the .tavis.yml and remove it from travis. I can do this.
Regarding the building and publishing the lib: I think we should use github actions for this too.
I am open for a video-session via https://meet.jit.si/ Just give me a ping. I live in the Berlin/Germany timezone.

**Comment by aviadhahami** [comment]
let's set a call for tday (14/11/2022) @ 20:00 Berlin TZ, does this work?

**Comment by aviadhahami** [comment]
@kr1sp1n do u think we can set a meeting for this week? :) let's do the handover

**Comment by kr1sp1n** [comment]
@aviadhahami I am sick at the moment and would love to have a meeting with you next week, ok? Have a great day!

**Comment by aviadhahami** [comment]
force-merging due to weird issue w/ codecov

**Pull request merged**
