### PR TITLE
switch to Postman Request from Request

### PR DESCRIPTION
**Pull request by pratikpc**
1. Maintained fork of Request
2. Easiest to switch to
3. No support for request-promise-native so we had to build our own

Need to discuss how to best handle what happens when request-promise already provided and how best to Unit Test
```javascript
    if (config['request-promise'] != null) {
      return rpObject(options);
    }
```

PS had to update from Istanbul to NYC. Any coverage testing was breaking on my Windows machine without it

### CODE REVIEW

**Comment by pratikpc** [comment]
@aviadhahami @kr1sp1n could you look into this?

**Comment by aviadhahami** [comment]
hey :) 
overall looks ok, I just can't do anything lib-wise until ownership transfer is complete
> https://github.com/kr1sp1n/node-vault/issues/150#issuecomment-1015688481

**Comment by pratikpc** [comment]
@aviadhahami I wanted to ask you and @kr1sp1n  about how to handle it when
1. Request Promise is already provided
2. Do we create a new Request-Library option to pass the Request Library?
3. How to unit test the Postman Request library

```js
    if (config['request-promise'] != null) {
      return rpObject(options);
    }
```
Currently am using this

**Comment by aviadhahami** [comment]
tbh I didn't dive into this yet.
Will do once ownership is transferred, until then we can't do anything 🤷‍♂️

**Comment by aviadhahami** [comment]
got the permissions (almost all what I need), trying to get this in asap

**Comment by aviadhahami** [comment]
@pratikpc do you mind updating the base for this PR? :)

**Comment by aviadhahami** [comment]
Closing in favor of https://github.com/nodevault/node-vault/pull/231

**Pull request closed without merging**
