### PR TITLE
Remove deprecated request

### PR DESCRIPTION
**Pull request by me23**
because of deprecated warnings i removed the dependencies for request

### CODE REVIEW

**Comment by aviadhahami** [comment]
@me23 - Hi! thx for the contribution

Do you believe the above implementation is robust enough to fit all use cases?
if so - please update the base for this PR and let's proceed :)

**Comment by bennyhodl** [comment]
Would like to see this merged. 
```
request  *
Severity: moderate
Server-Side Request Forgery in Request - https://github.com/advisories/GHSA-p8p7-x288-28g6
```

**Comment by aviadhahami** [comment]
@bennyhodl yes, I agree
as you can see, the repo was unmaintained for a while, I'm now pushing this forward :) 

Per this PR, please address my above question

**Comment by me23** [comment]
Hi, sorry i am a little bit lost here... My intention was to create a second pull-request for the replacement of the Request-package, but github appended this commits to my first pull-request instead.   

The first commit only adds the missing type definition, so i think this will not break anything and don't need more tests.

For the replacement for the Request-package, on my local side is all up-to-date, and the existing tests all passing. I don't see the conflicts which github mention above. Maybe someone could recheck my request-replacement and then help me to update the base...

Thanks

me23

**Comment by dhendo** [comment]
@me23 @aviadhahami This doesn't look too far off (not tested it in anger yet though) https://github.com/nodevault/node-vault/compare/master...TriggeredMessaging:node-vault:remove-request-fix-conflicts?expand=1

**Comment by aviadhahami** [comment]
Heya
cosing in favor of https://github.com/nodevault/node-vault/pull/231

**Pull request closed without merging**
