### PR TITLE
Added support for TLS Certificate based Authentication

### PR DESCRIPTION
**Pull request by sudiptosarkar**
Added support for TLS Certificate based Authentication to be able to get the token with client TLS Certificate, as is required according to #206

### CODE REVIEW

**Comment by aviadhahami** [comment]
@sudiptosarkar please fix the above issues so we can continue :)

**Review by aviadhahami — CHANGES_REQUESTED** [review]
awaiting pr fixes

**Comment by sudiptosarkar** [comment]
@aviadhahami, Done. Please approve the workflows.

**Comment by aviadhahami** [comment]
@sudiptosarkar please fix workflow errors 🙇

**Comment by sudiptosarkar** [comment]
> @sudiptosarkar please fix workflow errors bow

@aviadhahami, Done. Verified with `npm run lint` this time.

**Review by aviadhahami — APPROVED** [review]
lgtm

**Comment by aviadhahami** [comment]
thx for your contribution!

**Pull request merged**
